# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df8033f037f1d13887be8db5b6d18691f9469a97fd3a8f457b8180b1f2f0ac85ae9f7a1bd887548cb808e585a8f71a1f4bd21f6918dfb92d8d0046c504a8e32e
  mandrill_password: <%= ENV["mandrill_password"] %>
  mandrill_username: <%= ENV["mandrill_username"] %>
test:
  secret_key_base: f4ba88f0947bc8803fc4fcb0a5115b333dbacc33d115d1fa3b154d41b9a0b7c85dfde3b6bad060ac3ab7bcf53ea1d732d14f49fe25c03a80ffe4cd13708c6edb
  mandrill_password: <%= ENV["mandrill_password"] %>
  mandrill_username: <%= ENV["mandrill_username"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mandrill_password: <%= ENV["mandrill_password"] %>
  mandrill_username: <%= ENV["mandrill_username"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
